profiles:
  - dest: Comparison/Encounter
    leftIg: de.gematik.isik-basismodul#4.0.3
    rightIg: hl7.fhir.eu.hdr#0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKTerminKontaktMitGesundheitseinrichtung
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/encounter-eu-hdr