igs:
   - name: hl7.fhir.eu.mpd
     url: https://build.fhir.org/ig/hl7-eu/mpd/package.tgz
   - name: hl7.fhir.eu.laboratory
     url: https://build.fhir.org/ig/hl7-eu/laboratory/package.r4.tgz
profiles:
  - dest: Comparison/EU-Base-Location
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.base@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKStandort
    rightProfile: http://hl7.eu/fhir/base/StructureDefinition/location-eu
  - dest: Comparison/EU-Base-Organization
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.base@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKOrganisation
    rightProfile: http://hl7.eu/fhir/base/StructureDefinition/organization-eu
  - dest: Comparison/EU-Base-Patient
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.base@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKPatient
    rightProfile: http://hl7.eu/fhir/base/StructureDefinition/patient-eu
  - dest: Comparison/EU-Base-Practitioner
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.base@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKPersonImGesundheitsberuf
    rightProfile: http://hl7.eu/fhir/base/StructureDefinition/practitioner-eu
  - dest: Comparison/EU-Base-Address
    leftIg: de.basisprofil.r4@1.5.4
    rightIg: hl7.fhir.eu.base@0.1.0-ballot
    leftProfile: http://fhir.de/StructureDefinition/address-de-basis
    rightProfile: http://hl7.eu/fhir/base/StructureDefinition/Address-eu
  - dest: Comparison/HDR-Patient
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKPatient
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/patient-eu-hdr
  - dest: Comparison/HDR-Encounter
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKKontaktGesundheitseinrichtung
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/encounter-eu-hdr
  - dest: Comparison/HDR-Composition
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKBerichtSubSysteme
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/composition-eu-hdr
  - dest: Comparison/HDR-AllergyIntolerance
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKAllergieUnvertraeglichkeit
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/allergyIntolerance-eu-hdr
  - dest: Comparison/HDR-Procedure
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKProzedur
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/procedure-eu-hdr
  - dest: Comparison/HDR-Condition
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKDiagnose
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/condition-eu-hdr
  - dest: Comparison/HDR-Patient-obl
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKPatient
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/patient-obl-eu-hdr
  - dest: Comparison/HDR-Encounter-obl
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKKontaktGesundheitseinrichtung
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/encounter-obl-eu-hdr
  - dest: Comparison/HDR-Composition-obl
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKBerichtSubSysteme
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/composition-obl-eu-hdr
  - dest: Comparison/HDR-AllergyIntolerance-obl
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKAllergieUnvertraeglichkeit
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/allergyIntolerance-obl-eu-hdr
  - dest: Comparison/HDR-Procedure-obl
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr#0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKProzedur
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/procedure-obl-eu-hdr
  - dest: Comparison/HDR-Condition-obl
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.hdr@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKDiagnose
    rightProfile: http://hl7.eu/fhir/hdr/StructureDefinition/condition-obl-eu-hdr
  - dest: Comparison/EPS-Patient
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.eps@0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKPatient
    rightProfile: http://hl7.eu/fhir/eps/StructureDefinition/patient-eu-eps
  - dest: Comparison/EPS-Condition
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.eps@0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKDiagnose
    rightProfile: http://hl7.eu/fhir/eps/StructureDefinition/condition-eu-eps
  - dest: Comparison/EPS-Procedure
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.eps@0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKProzedur
    rightProfile: http://hl7.eu/fhir/eps/StructureDefinition/procedure-eu-hdr
  - dest: Comparison/EPS-AllergyIntolerance
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.eps@0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKAllergieUnvertraeglichkeit
    rightProfile: http://hl7.eu/fhir/eps/StructureDefinition/allergyIntolerance-eu-eps
  - dest: Comparison/EPS-Medication
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.eps@0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKMedikament
    rightProfile: http://hl7.eu/fhir/eps/StructureDefinition/Medication-eu-eps
  - dest: Comparison/EPS-MedicationStatement
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.eps@0.0.1-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKMedikationsInformation
    rightProfile: http://hl7.eu/fhir/eps/StructureDefinition/MedicationStatement-eu-eps
  - dest: Comparison/MPD-Medication
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.mpd@0.1.0
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKMedikament
    rightProfile: http://hl7.eu/fhir/mpd/StructureDefinition/Medication-eu-mpd
  - dest: Comparison/MPD-MedicationRequest
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.mpd@0.1.0-ballot
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKMedikationsVerordnung
    rightProfile: http://hl7.eu/fhir/mpd/StructureDefinition/MedicationRequest-eu-mpd
  - dest: Comparison/Laboratory-ObservationLabResult
    leftIg: de.gematik.isik@5.0.0
    rightIg: hl7.fhir.eu.laboratory#0.2.0-ci
    leftProfile: https://gematik.de/fhir/isik/StructureDefinition/ISiKLaboruntersuchung
    rightProfile: http://hl7.eu/fhir/laboratory/StructureDefinition/Observation-resultslab-eu-lab
