instances:
  - name: Patient-DorisQuelle
    file: PackagesForCache/de.gematik.isik#5.0.0-rc/package/examples/Patient-DorisQuelle.json
    profile: http://hl7.eu/fhir/eps/StructureDefinition/patient-eu-eps