instances:
  - name: Patient-DorisQuelle
    file: PackagesForCache/de.gematik.isik#5.0.0-rc/package/examples/Patient-DorisQuelle.json
    ig: hl7.fhir.eu.eps.r4@0.0.1-ci -ig hl7.fhir.eu.base.r4@0.1.0-ci
    profile: http://hl7.eu/fhir/eps/StructureDefinition/patient-eu-eps