name: Setup Tools

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:

      # apt-get update
      # apt-get install -y jq curl
      - name: 🔧 Install yq and jq (manuell)
        run: |
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y jq curl
          else
            apt-get update
            apt-get install -y jq curl
          fi

          mkdir -p "$HOME/.local/bin"
          YQ_VERSION=v4.40.5
          curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -o "$HOME/.local/bin/yq"
          chmod +x "$HOME/.local/bin/yq"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: ☕ Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 📅 Set current date for cache
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 🔄 Restore cache for validator_cli.jar
        uses: actions/cache@v3
        with:
          path: tmp/validator_cli.jar
          key: ${{ runner.os }}-validator-cli-${{ env.TODAY }}
          restore-keys: |
            ${{ runner.os }}-validator-cli-

      - name: 😇 Download validator_cli.jar (if not cached)
        run: |
          mkdir -p tmp
          if [ ! -f tmp/validator_cli.jar ]; then
            echo "Cache miss – downloading"
            curl -L -o tmp/validator_cli.jar http://horvac.de/org.hl7.fhir.validation.cli-6.4.0.jar
          else
            echo "✅ Using cached version"
          fi

      - name: 💾 Save cache for validator_cli.jar
        uses: actions/cache@v3
        with:
          path: tmp/validator_cli.jar
          key: ${{ runner.os }}-validator-cli-${{ env.TODAY }}